// LLM-based summarization for OCR and screenshot content
use anyhow::{Context, Result};
use serde::{Deserialize, Serialize};

use crate::inference::llama::{LlamaModel, LlamaParams};
use crate::processing::text_processing::{ExtractedEntities, StructureType};

/// Summary generated by LLM
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SummaryResult {
    pub summary: String,
    pub key_points: Vec<String>,
    #[serde(default)]
    pub content_type: ContentType,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default, PartialEq)]
#[serde(rename_all = "snake_case")]
pub enum ContentType {
    #[default]
    General,
    Code,
    Terminal,
    WebPage,
    Document,
    Design,
    Chat,
}

impl From<StructureType> for ContentType {
    fn from(structure: StructureType) -> Self {
        match structure {
            StructureType::Code => ContentType::Code,
            StructureType::Terminal => ContentType::Terminal,
            StructureType::Table | StructureType::List | StructureType::Plain => {
                ContentType::General
            }
        }
    }
}

/// Generate summary using LLM
pub async fn summarize_with_llm(
    model: &LlamaModel,
    text: &str,
    caption: Option<&str>,
    entities: Option<&ExtractedEntities>,
    content_type: ContentType,
) -> Result<SummaryResult> {
    // Build prompt based on content type and available information
    let prompt = build_summarization_prompt(text, caption, entities, &content_type);

    // Generate response with timeout
    let params = LlamaParams::default();

    let response = tokio::task::spawn_blocking({
        let model = model.clone();
        let prompt = prompt.clone();
        move || model.generate(&prompt, &params)
    })
    .await
    .context("LLM task panicked")??;

    // Parse JSON response
    parse_summary_response(&response, content_type)
}

/// Build summarization prompt for LLM
/// If caption is provided, uses caption as primary input and ignores OCR text
/// If caption is not provided, uses OCR text
fn build_summarization_prompt(
    text: &str,
    caption: Option<&str>,
    entities: Option<&ExtractedEntities>,
    content_type: &ContentType,
) -> String {
    // Priority: Use caption if available, otherwise use OCR text
    let (primary_text, is_caption) = if let Some(cap) = caption {
        if !cap.is_empty() && !cap.starts_with("Screenshot") {
            log::info!("Using caption (vision model) as primary input for LLM summarization");
            (cap.to_string(), true)
        } else {
            log::info!("Caption is placeholder, using OCR text for LLM summarization");
            // Apply aggressive cleaning for OCR text
            let processor = crate::processing::text_processing::TextProcessor::new();
            (processor.clean_screenshot_ocr(text), false)
        }
    } else {
        log::info!("No caption available, using OCR text for LLM summarization");
        // Apply aggressive cleaning for OCR text
        let processor = crate::processing::text_processing::TextProcessor::new();
        (processor.clean_screenshot_ocr(text), false)
    };

    // Smart truncation: Keep up to 2000 chars, truncate at sentence boundary
    let text_preview = if primary_text.len() > 2000 {
        // Try to find last sentence ending before 2000 chars
        let truncate_at = primary_text[..2000]
            .rfind(". ")
            .or_else(|| primary_text[..2000].rfind(".\n"))
            .or_else(|| primary_text[..2000].rfind("! "))
            .or_else(|| primary_text[..2000].rfind("? "))
            .map(|pos| pos + 1) // Include the period/punctuation
            .unwrap_or(2000);

        let preview = &primary_text[..truncate_at];
        log::debug!(
            "Truncating text from {} to {} chars at sentence boundary",
            primary_text.len(),
            truncate_at
        );
        preview.to_string()
    } else {
        log::debug!(
            "Using full text for summarization ({} chars)",
            primary_text.len()
        );
        primary_text.clone()
    };

    // Build entities section
    let entities_section = if let Some(ent) = entities {
        let mut parts = Vec::new();

        if !ent.urls.is_empty() {
            parts.push(format!("URLs: {}", ent.urls.join(", ")));
        }
        if !ent.emails.is_empty() {
            parts.push(format!("Emails: {}", ent.emails.join(", ")));
        }
        if !ent.commands.is_empty() {
            parts.push(format!("Commands: {}", ent.commands.join("; ")));
        }

        if parts.is_empty() {
            String::new()
        } else {
            format!("\n\nExtracted Entities:\n{}", parts.join("\n"))
        }
    } else {
        String::new()
    };

    // Build input label based on whether we're using caption or OCR
    let input_label = if is_caption {
        "IMAGE CAPTION (Vision Model Output):"
    } else {
        "OCR TEXT FROM SCREENSHOT:"
    };

    let instructions = if is_caption {
        r#"STEP 1 - UNDERSTAND THE CAPTION:
The caption is generated by a vision model that describes the image content. It should already be a clean, meaningful description.

STEP 2 - EXTRACT KEY INFORMATION:
- Identify the main subject/topic from the caption
- Note any important details or context mentioned
- Understand what type of content is being shown

STEP 3 - CREATE A CONCISE SUMMARY:
- Use the caption as the primary source of information
- Create a summary that captures the essence of what the vision model detected"#
    } else {
        r#"STEP 1 - IGNORE UI CHROME:
The OCR text contains both the main content AND user interface elements. You MUST ignore:
- Browser/app interface: tabs, toolbars, buttons (x, +, ⋮), app names in titlebars
- Navigation: arrows, "Back", "Forward", menu items
- Timestamps and status: "11:28 PM", "Online", "Yesterday", "2 min ago"
- Window decorations: minimize/maximize buttons, window titles
- User labels: standalone names like "You", "Guest", participant badges without context

STEP 2 - IDENTIFY MAIN CONTENT:
Focus ONLY on the main content area:
- For chats: the actual conversation messages
- For code: the code itself, not editor UI
- For documents: the document text, not toolbar/menus
- For websites: the page content, not browser chrome
- For terminals: the commands and output, not window title

STEP 3 - READ WHAT IS ACTUALLY WRITTEN:
- Extract the real subject/topic from the TEXT ITSELF
- Use actual words and phrases that appear in the content
- Do NOT invent topics based on assumptions or fragments
- If content is fragmented/unclear, summarize only the readable parts"#
    };

    let input_type_description = if is_caption {
        "image captions"
    } else {
        "OCR text from screenshots"
    };

    format!(
        r#"<|im_start|>system
You are a summarization assistant. Your job is to read {} and create accurate summaries. Respond ONLY with valid JSON, no other text.<|im_end|>
<|im_start|>user
{}:
---
{}
{}
---

INSTRUCTIONS:

{}

STEP 4 - FORMAT YOUR SUMMARY:
Use this format: "[Content Type]: [Main Subject/Topic]"

Examples:
- "Code: React authentication component with JWT validation"
- "Conversation: Travel discussion about island destinations and tourism"
- "Terminal: Docker container debugging and log analysis"
- "Document: Product requirements for user dashboard feature"
- "Webpage: Python async programming tutorial"

CRITICAL RULES:
1. Base summary ONLY on words that ACTUALLY APPEAR in the content
2. Do NOT fabricate topics - use actual content from the input
3. If unclear, be honest: "Screenshot with fragmented text" rather than guessing

Generate summary (max 150 chars) and 2-4 key points from the content:
{{"summary":"[Type]: [Actual topic from content]","key_points":["key point 1","key point 2"]}}

Remember: Read the actual content, don't invent topics.<|im_end|>
<|im_start|>assistant
{{"#,
        input_type_description, input_label, text_preview, entities_section, instructions
    )
}

/// Parse LLM JSON response for summary
fn parse_summary_response(response: &str, content_type: ContentType) -> Result<SummaryResult> {
    log::debug!("Raw LLM summary response: {}", response);

    // Handle case where model continues from our priming "{{"
    let json_str = if response.trim_start().starts_with('"') && response.contains('}') {
        // Missing opening brace - add it
        let end = response.rfind('}').unwrap_or(response.len());
        if end < response.len() {
            format!("{{{}", &response[..end + 1])
        } else {
            format!("{{{}}}", response)
        }
    } else {
        // Normal case - extract JSON from response
        let json_start = response.find('{');
        let json_end = response.rfind('}');

        if json_start.is_none() || json_end.is_none() {
            log::warn!("No JSON found in LLM response, using fallback");
            return Ok(create_fallback_summary(response, content_type));
        }

        response[json_start.unwrap()..json_end.unwrap() + 1].to_string()
    };

    log::debug!("Extracted JSON: {}", json_str);

    // Try to parse JSON
    match serde_json::from_str::<SummaryResult>(&json_str) {
        Ok(mut result) => {
            result.content_type = content_type;

            // Validate summary length
            if result.summary.len() > 200 {
                result.summary = format!("{}...", &result.summary[..197]);
            }

            Ok(result)
        }
        Err(e) => {
            log::error!("JSON parse error: {}", e);
            log::error!("Attempted to parse: {}", json_str);

            // Try to fix common issues
            let cleaned = json_str
                .replace(",}", "}")
                .replace(",]", "]")
                .replace("\n", " ");

            match serde_json::from_str::<SummaryResult>(&cleaned) {
                Ok(mut result) => {
                    result.content_type = content_type;
                    Ok(result)
                }
                Err(_) => {
                    log::warn!("Failed to parse cleaned JSON, using fallback");
                    Ok(create_fallback_summary(response, content_type))
                }
            }
        }
    }
}

/// Create a fallback summary when LLM parsing fails
fn create_fallback_summary(text: &str, content_type: ContentType) -> SummaryResult {
    // Sanitize text - remove JSON formatting if present
    let cleaned_text = if text.trim().starts_with('{') || text.contains(r#""summary""#) {
        // This looks like malformed JSON - try to extract readable content
        log::debug!("Detected JSON-like text in fallback, sanitizing...");

        // Try to extract summary field value
        if let Some(summary_start) = text.find(r#""summary""#) {
            let after_label = &text[summary_start + 9..]; // Skip past "summary"
            if let Some(quote_start) = after_label.find('"') {
                let value_start = quote_start + 1;
                if let Some(quote_end) = after_label[value_start..].find('"') {
                    let summary_text = &after_label[value_start..value_start + quote_end];
                    // Unescape common JSON escapes
                    return SummaryResult {
                        summary: summary_text.replace(r#"\""#, "\"").replace(r#"\n"#, " "),
                        key_points: vec![],
                        content_type,
                    };
                }
            }
        }

        // Fallback: strip JSON characters
        text.replace(['{', '}', '[', ']', '"'], "")
            .split(',')
            .next()
            .unwrap_or(text)
            .trim()
            .to_string()
    } else {
        text.to_string()
    };

    // Extract first 2-3 sentences or first 200 chars as summary
    let summary = extract_first_n_sentences(&cleaned_text, 3, 200).unwrap_or_else(|| {
        if cleaned_text.len() > 200 {
            format!("{}...", &cleaned_text[..197])
        } else {
            cleaned_text.clone()
        }
    });

    SummaryResult {
        summary,
        key_points: vec![],
        content_type,
    }
}

/// Extract first complete sentence from text
fn extract_first_sentence(text: &str) -> Option<String> {
    let text = text.trim();

    // Find sentence endings
    let sentence_endings = [". ", "! ", "? ", ".\n", "!\n", "?\n"];

    let mut end_pos = None;
    for ending in sentence_endings.iter() {
        if let Some(pos) = text.find(ending) {
            if end_pos.is_none() || pos < end_pos.unwrap() {
                end_pos = Some(pos + ending.len() - 1);
            }
        }
    }

    end_pos.map(|pos| {
        let sentence = text[..=pos].trim().to_string();
        if sentence.len() > 150 {
            format!("{}...", &sentence[..147])
        } else {
            sentence
        }
    })
}

/// Extract first N sentences from text, up to max_length
fn extract_first_n_sentences(text: &str, n: usize, max_length: usize) -> Option<String> {
    let text = text.trim();
    let sentence_endings = [". ", "! ", "? ", ".\n", "!\n", "?\n"];

    let mut sentences = Vec::new();
    let mut current_pos = 0;
    let mut total_length = 0;

    for _ in 0..n {
        if current_pos >= text.len() {
            break;
        }

        // Find next sentence ending
        let remaining = &text[current_pos..];
        let mut next_end = None;

        for ending in sentence_endings.iter() {
            if let Some(pos) = remaining.find(ending) {
                if next_end.is_none() || pos < next_end.unwrap() {
                    next_end = Some(pos + ending.len());
                }
            }
        }

        if let Some(end) = next_end {
            let sentence = remaining[..end].trim();
            if total_length + sentence.len() > max_length {
                break;
            }
            sentences.push(sentence);
            total_length += sentence.len();
            current_pos += end;
        } else {
            // No more sentences, take remaining text if under limit
            if total_length + remaining.len() <= max_length {
                sentences.push(remaining.trim());
            }
            break;
        }
    }

    if sentences.is_empty() {
        None
    } else {
        Some(sentences.join(" "))
    }
}

/// Generate a quick rule-based summary as fallback
/// Uses caption (vision model output) as primary source if available, otherwise uses OCR text
pub fn generate_rule_based_summary(
    text: &str,
    caption: Option<&str>,
    entities: &ExtractedEntities,
    content_type: ContentType,
) -> SummaryResult {
    let mut parts = Vec::new();
    let mut key_points = Vec::new();

    // Add content type prefix
    let type_prefix = match content_type {
        ContentType::Code => "Code:",
        ContentType::Terminal => "Terminal:",
        ContentType::WebPage => "Web:",
        ContentType::Document => "Doc:",
        ContentType::Design => "Design:",
        ContentType::Chat => "Chat:",
        ContentType::General => "",
    };

    if !type_prefix.is_empty() {
        parts.push(type_prefix.to_string());
    }

    // Priority: Use caption (vision model) if available, otherwise use OCR text
    if let Some(cap) = caption {
        if !cap.is_empty() && !cap.starts_with("Screenshot") {
            log::debug!("Using caption (vision model) for rule-based summary");
            // Use caption as primary source
            let caption_excerpt = if cap.len() > 100 {
                format!("{}...", &cap[..97])
            } else {
                cap.to_string()
            };
            parts.push(caption_excerpt);
        } else {
            // Caption is placeholder, fall back to OCR text
            log::debug!("Caption is placeholder, using OCR text for rule-based summary");
            let text_excerpt = if text.len() > 100 {
                format!("{}...", &text[..97])
            } else {
                text.to_string()
            };
            if !text_excerpt.is_empty() {
                parts.push(text_excerpt);
            }
        }
    } else {
        // No caption available, use OCR text
        log::debug!("No caption available, using OCR text for rule-based summary");
        let text_excerpt = if text.len() > 100 {
            format!("{}...", &text[..97])
        } else {
            text.to_string()
        };
        if !text_excerpt.is_empty() {
            parts.push(text_excerpt);
        }
    }

    // Add entities as key points (but don't add to summary if we have caption)
    if !entities.urls.is_empty() {
        key_points.push(format!("URL: {}", entities.urls[0]));
    }

    if !entities.commands.is_empty() {
        let cmd = &entities.commands[0];
        if cmd.len() < 80 {
            key_points.push(cmd.clone());
        }
    }

    let summary = if parts.is_empty() {
        format!("{} content", type_prefix)
    } else {
        parts.join(" ")
    };

    // Limit summary to 150 chars
    let summary = if summary.len() > 150 {
        format!("{}...", &summary[..147])
    } else {
        summary
    };

    SummaryResult {
        summary,
        key_points,
        content_type,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_extract_first_sentence() {
        let text = "This is the first sentence. This is the second.";
        assert_eq!(
            extract_first_sentence(text).unwrap(),
            "This is the first sentence."
        );
    }

    #[test]
    fn test_fallback_summary() {
        let text = "Some random text without proper structure";
        let summary = create_fallback_summary(text, ContentType::General);
        assert!(!summary.summary.is_empty());
        assert!(summary.summary.len() <= 150);
    }

    #[test]
    fn test_rule_based_summary() {
        let entities = ExtractedEntities {
            urls: vec!["https://example.com".to_string()],
            emails: vec![],
            file_paths: vec![],
            code_snippets: vec![],
            commands: vec!["npm install".to_string()],
        };

        let summary = generate_rule_based_summary(
            "Some text content here",
            Some("A screenshot"),
            &entities,
            ContentType::Terminal,
        );

        assert!(summary.summary.contains("Terminal:") || summary.summary.contains("https://"));
        assert!(!summary.key_points.is_empty());
    }
}
